### ISSUE TITLE
Cross platform file path incompatabilities

### ISSUE THREAD

**Issue by DaveLAtch** [DEQrmichie/heatsource-9#1]
I'm running into issues while working on semi-automating heatesource runs. I'm running my python 2.7 scripts on a Win 10 box, but referring to heatsource control, input and output directories on a linux server on our network. In order to avoid OS dependent file paths I've adopted forward slash notation in all my file path references.  This is causing scripts like HS9_Setup_Model_inputs.py to raise errors when it checks for OS system dependent file path notation (eg. line 407 & 410 in HS9_Setup_Model_inputs.py). 

platform.system() is identifying me as a Windows user and requiring '\' ending in my path statements but I am referring to paths on a linux box which requires '/'.  

I have not found any obvious workarounds for this issue.

**Comment by rmichie** [comment]
Thanks for the message DaveLAtch,

Yes, the code as currently written assumes that the model and the machine where the inputs and outputs are saved have the same OS.  Is it a possibility for you to install the model on linux?

The quick and dirty approach to get you going is to simply comment out [those lines](https://github.com/rmichie/heatsource-9/blob/186a3d860216583422535df3001b871148becb8d/HS9_py2/heatsource9/ModelSetup/Inputs.py#L407-L411). Those lines of code are there for error checking so the model should run normally.

I will think about how best to address this.

**Comment by DaveLAtch** [comment]
I might be able to offer some help. It seems that adopting a “forward slash” convention throughout might offer a solution – I typically use forward slash paths even when working with Windows.  I’m not sure how this would interact with all the code you’ve already got using os.path… functionality and whatnot but I’d be happy to take a look at it as I continue to try to automate our processes.  This isn’t a time critical issue for me because, as you say, there are workarounds.

This is a low priority project for me right now, but I’d be happy to work on it as time allows and offer up some patches if I can manage to code them up.  Up to you of course to determine if they should be incorporated in heatsource9.01.

Really nice work by the way. I’m having to up my game in python to meet the standards you’ve set with your code.

Cheers,

Dave

David L. Atchison, Ph.D.
Data Analyst
The Freshwater Trust
700 SW Taylor St.  Suite 200
Portland, OR 97205
(503) 222-9091 x 43
dave@thefreshwatertrust.org<mailto:dave@thefreshwatertrust.org>
www.thefreshwatertrust.org<http://www.thefreshwatertrust.org/>

**Comment by DEQrmichie** [comment]
This has been addressed in cb31716.
