### ISSUE TITLE
Changes to get things running

### ISSUE THREAD

**Issue by dharp** [DEQrmichie/heatsource-9#13]
I made the following changes to get things running:

![image](https://github.com/DEQrmichie/heatsource-9/assets/2457348/070d252a-5466-4ff1-9a02-c5cfdf4b94ad)

I'm wondering if they can be incorporated into the repo?

Thanks,
Dylan

**Comment by DEQrmichie** [comment]
Thanks @dharp . This was fixed in 89ea4e3. Sorry it took so long.

**Comment by dharp** [comment]
Thanks, @DEQrmichie ! I've made some other changes in our fork that it would be great to run by you if you are interested.

**Comment by DEQrmichie** [comment]
@dharp , yes, would be good to connect. I was browsing your repository yesterday and noticed some of those changes. I'll contact you via email.
