### ISSUE TITLE
Not saving the whole simulation timeframe when dealing with small number of nodes

### ISSUE THREAD

**Issue by coltenelkin** [DEQrmichie/heatsource-9#17]
Still exploring the root of this issue, but when dealing with small (~0.8km or less) streams with nodes spaced every 25m, the output Heat_SRx csv files do not write values for the entire simulation. For instance, with two heatsource control files with identical inputs except for the streamlength and land cover input data file name, the longer stream runs the full simulation period of July 1 - October 29. The shorter stream, however, only writes data through October 21.  

As a quick fix, I lengthened the computation window well past the end of our needed simulation (went to November 8th, now have calculated Heat_SRx files through the morning of November 1st) and just truncated at the end of our simulation window.

**Comment by DEQrmichie** [comment]
I think this issue might have been fixed in b0fee28.
